import { asc, eq, sql, count, ilike } from 'drizzle-orm';
import {
  formatPaginatedResult,
  type PaginatedResult,
} from '../../shared/pagination.ts';
import { db } from '../../db/client.ts';
import { employees, locations } from '../../db/schema/index.ts';
import ApiError from '../../shared/api-error.ts';

export interface PublicLocation {
  id: string;
  name: string;
}

export function publicLocation(
  l: Readonly<typeof locations.$inferSelect>,
): PublicLocation {
  return {
    id: l.id,
    name: l.name,
  };
}

export interface LocationCreateInput {
  name: string;
}

export interface LocationPatchInput {
  name: string;
}

export async function listLocations(
  page: number = 1,
  limit: number = 10,
  search?: string,
): Promise<PaginatedResult<PublicLocation>> {
  const offset = (page - 1) * limit;
  const whereClause = search ? ilike(locations.name, `%${search}%`) : undefined;
  // Page query and count are independent, so run them in parallel. The
  // explicit order keeps pages stable (without it Postgres may return rows in
  // any order, so items can repeat or go missing between pages).
  const [rows, [countRes]] = await Promise.all([
    db
      .select()
      .from(locations)
      .where(whereClause)
      .orderBy(asc(locations.createdAt), asc(locations.id))
      .limit(limit)
      .offset(offset),
    db.select({ total: count() }).from(locations).where(whereClause),
  ]);
  return formatPaginatedResult(
    rows.map(publicLocation),
    countRes?.total ?? 0,
    page,
    limit,
  );
}

export async function createLocation(
  input: LocationCreateInput,
): Promise<PublicLocation> {
  // The id is generated by the database (uuid default), so the admin only
  // has to type the display name.
  const [row] = await db
    .insert(locations)
    .values({ name: input.name })
    .returning();
  if (!row) {
    throw Object.assign(new ApiError('Inserted location not found', 500), {
      errorCode: 'INTERNAL_ERROR',
    });
  }
  return publicLocation(row);
}

export async function updateLocation(
  id: string,
  patch: LocationPatchInput,
): Promise<PublicLocation> {
  // One round trip: update and read back; no row means the id is unknown.
  const [updated] = await db
    .update(locations)
    .set(patch)
    .where(eq(locations.id, id))
    .returning();
  if (!updated) {
    throw Object.assign(new ApiError('Location not found', 404), {
      errorCode: 'LOCATION_NOT_FOUND',
    });
  }
  return publicLocation(updated);
}

// Hard delete - refused when any employee still references the location.
// employees.location_id has ON DELETE restrict.
export async function deleteLocation(id: string): Promise<void> {
  // A location that does not exist has no employees, so checking references
  // first and then deleting needs only two queries.
  const refs = await db
    .select({ c: sql<number>`count(*)::int` })
    .from(employees)
    .where(eq(employees.locationId, id));
  const refCount = refs[0]?.c ?? 0;
  if (refCount > 0) {
    throw Object.assign(
      new ApiError(
        `Cannot delete: ${refCount} employee(s) still reference this location.`,
        409,
      ),
      { errorCode: 'LOCATION_IN_USE' },
    );
  }
  const deleted = await db
    .delete(locations)
    .where(eq(locations.id, id))
    .returning({ id: locations.id });
  if (deleted.length === 0) {
    throw Object.assign(new ApiError('Location not found', 404), {
      errorCode: 'LOCATION_NOT_FOUND',
    });
  }
}
